local M = {}

M.build = function(c)
    return {
        -- Basic editor highlights
        ColorColumn = { bg = c.shade },
        Conceal = { fg = c.shade },
        CurSearch = { fg = c.bg, bg = c.clay, bold = true },
        Cursor = { fg = c.bg, bg = c.fg },
        lCursor = { fg = c.bg, bg = c.seed },
        CursorIM = { link = 'Cursor' },
        CursorColumn = { bg = c.float_bg },
        CursorLine = { bg = c.float_bg },
        Directory = { fg = c.moss, bold = true },
        DiffAdd = { fg = c.grass, bg = c.diff_add_bg },
        DiffChange = { bg = c.diff_change_bg },
        DiffDelete = { fg = c.clay, bg = c.diff_delete_bg },
        DiffText = { fg = c.diff_text_bg, reverse = true },
        DiffTextAdd = { link = 'DiffText' },
        EndOfBuffer = { link = 'NonText' },
        TermCursor = { reverse = true },
        OkMsg = { fg = c.grass },
        WarningMsg = { fg = c.sand },
        ErrorMsg = { fg = c.clay },
        StderrMsg = { link = 'ErrorMsg' },
        StdoutMsg = {},
        WinSeparator = { link = 'LineNr' },
        Folded = { fg = c.bark, bg = c.float_bg },
        FoldColumn = { fg = c.bark, bold = true },
        SignColumn = { fg = c.bark },
        IncSearch = { link = 'CurSearch' },
        Substitute = { fg = c.bg, bg = c.sand },
        LineNr = { fg = c.shade },
        CursorLineNr = { fg = c.grass, bold = true },
        CursorLineFold = { link = 'FoldColumn' },
        CursorLineSign = { link = 'SignColumn' },
        MatchParen = { fg = c.clay, bold = true, underline = true },
        ModeMsg = { fg = c.fg },
        MsgArea = {},
        MsgSeparator = { link = 'StatusLine' },
        MoreMsg = { fg = c.tree },
        NonText = { fg = c.shade },
        Normal = { fg = c.fg, bg = c.bg },
        NormalFloat = { bg = c.float_bg },
        FloatBorder = { fg = c.bark, bg = c.bg },
        FloatShadow = { bg = '#051a18', blend = 80 },
        FloatTitle = { fg = c.fg, bg = c.focus_bg, bold = true },
        FloatFooter = { link = 'FloatTitle' },
        NormalNC = {},
        Pmenu = { bg = c.float_bg },
        PmenuSel = { fg = c.bg, bg = c.grass, blend = 0 },
        PmenuKind = { fg = c.moss },
        PmenuKindSel = { link = 'PmenuSel' },
        PmenuExtra = { fg = c.bark },
        PmenuExtraSel = { link = 'PmenuExtraSel' },
        PmenuSbar = { link = 'Pmenu' },
        PmenuThumb = { bg = c.bark },
        PmenuMatch = { fg = c.clay, bold = true },
        PmenuMatchSel = { bold = true },
        PmenuBorder = { link = 'FloatBorder' },
        PmenuShadow = { link = 'FloatShadow' },
        ComplMatchIns = {},
        PreInsert = { link = 'Added' },
        ComplHint = { link = 'NonText' },
        ComplHintMore = { link = 'MoreMsg' },
        Question = { link = 'MoreMsg' },
        QuickFixLine = { link = 'Search' },
        Search = { fg = c.bg, bg = c.grass },
        SnippetTabstop = { bg = c.focus_bg },
        SnippetTabstopActive = { link = 'SnippetTabstop' },
        SpecialKey = { link = 'Special' },
        SpellBad = { undercurl = true, sp = c.clay },
        SpellCap = { undercurl = true, sp = c.sand },
        SpellLocal = { undercurl = true, sp = c.tree },
        SpellRare = { link = 'SpellLocal' },
        StatusLine = { fg = c.moss },
        StatusLineNC = { fg = c.bark },
        StatusLineTerm = { link = 'StatusLine' },
        StatusLineTermNC = { link = 'StatusLineNC' },
        TabLine = { link = 'StatusLineNC' },
        TabLineFill = { link = 'TabLine' },
        TabLineSel = { link = 'StatusLine' },
        Title = { fg = c.fg, bold = true },
        Visual = { fg = c.bg, bg = c.tree },
        Whitespace = { fg = c.shade, bg = c.shadow_bg },
        WildMenu = { link = 'PmenuSel' },
        WinBar = { link = 'StatusLine' },
        WinBarNC = { link = 'StatusLineNC' },

        -- Syntax highlights
        Comment = { fg = c.bark },
        Constant = { fg = c.fg },
        String = { fg = c.rock },
        Character = { fg = c.clay },
        Number = { fg = c.seed },
        Boolean = { fg = c.sand },
        Float = { link = 'Number' },
        Identifier = { fg = c.identifier_fg },
        Function = { fg = c.function_fg },
        Statement = { fg = c.tree, bold = true },
        Conditional = { link = 'Statement' },
        Repeat = { link = 'Statement' },
        Label = { link = 'Statement' },
        Operator = { fg = c.seed },
        Keyword = { fg = c.tree, bold = true },
        Exception = { link = 'Statement' },
        PreProc = { fg = c.tree },
        Include = { link = 'PreProc' },
        Define = { link = 'PreProc' },
        Macro = { link = 'PreProc' },
        PreCondit = { link = 'PreProc' },
        Type = { fg = c.grass, bold = true },
        StorageClass = { link = 'Type' },
        Structure = { link = 'Type' },
        Typedef = { link = 'Type' },
        Special = { fg = c.special_fg },
        SpecialChar = { link = 'Special' },
        Tag = { link = 'Special' },
        Delimiter = { fg = c.delimiter_fg },
        SpecialComment = { link = 'Special' },
        Debug = { link = 'Special' },
        Underlined = { fg = c.grass, underline = true },
        Ignore = { fg = c.bark },
        Error = { fg = c.clay, reverse = true },
        Todo = { fg = c.sand, bold = true, underline = true },
        Added = { fg = c.grass },
        Changed = { fg = c.moss },
        Removed = { fg = c.clay },

        -- Diagnostic
        DiagnosticError = { fg = c.clay },
        DiagnosticWarn = { fg = c.rock },
        DiagnosticInfo = { fg = c.tree },
        DiagnosticHint = { fg = c.moss },
        DiagnosticOk = { fg = c.grass },
        DiagnosticUnderlineError = { underline = true, sp = c.clay },
        DiagnosticUnderlineWarn = { underline = true, sp = c.rock },
        DiagnosticUnderlineInfo = { underline = true, sp = c.tree },
        DiagnosticUnderlineHint = { underline = true, sp = c.moss },
        DiagnosticUnderlineOk = { underline = true, sp = c.grass },
        DiagnosticDeprecated = { strikethrough = true },
        DiagnosticUnnecessary = { underline = true },

        -- Treesitter
        ['@variable'] = { link = 'Identifier' },
        ['@variable.builtin'] = { link = 'Special' },
        ['@variable.parameter'] = { fg = c.fg },
        ['@variable.parameter.builtin'] = { link = 'Special' },
        ['@variable.member'] = { link = '@variable' },
        ['@constant'] = { link = 'Constant' },
        ['@constant.builtin'] = { link = 'Special' },
        ['@constant.macro'] = { link = '@constant' },
        ['@module'] = { link = 'Structure' },
        ['@module.builtin'] = { link = 'Special' },
        ['@label'] = { link = 'Label' },
        ['@string'] = { link = 'String' },
        ['@string.documentation'] = { link = '@string' },
        ['@string.regexp'] = { link = 'Special' },
        ['@string.escape'] = { link = 'Special' },
        ['@string.special'] = { link = 'Special' },
        ['@string.special.url'] = { link = 'Underlined' },
        ['@character'] = { link = 'Character' },
        ['@character.special'] = { link = 'Special' },
        ['@boolean'] = { link = 'Boolean' },
        ['@number'] = { link = 'Number' },
        ['@number.float'] = { link = '@number' },
        ['@type'] = { link = 'Type' },
        ['@type.builtin'] = { link = 'Special' },
        ['@type.definition'] = { link = '@type' },
        ['@attribute'] = { link = 'PreProc' },
        ['@attribute.builtin'] = { link = 'Special' },
        ['@property'] = { link = 'Identifier' },
        ['@function'] = { link = 'Function' },
        ['@function.builtin'] = { link = 'Special' },
        ['@function.call'] = { link = '@function' },
        ['@function.macro'] = { link = '@function' },
        ['@function.method'] = { link = '@function' },
        ['@constructor'] = { link = 'Special' },
        ['@operator'] = { link = 'Operator' },
        ['@keyword'] = { link = 'Keyword' },
        ['@keyword.coroutine'] = { link = '@keyword' },
        ['@keyword.function'] = { link = '@keyword' },
        ['@keyword.operator'] = { link = '@keyword' },
        ['@keyword.import'] = { link = 'PreProc' },
        ['@keyword.type'] = { link = '@keyword' },
        ['@keyword.modifier'] = { link = '@keyword' },
        ['@keyword.repeat'] = { link = 'Repeat' },
        ['@keyword.return'] = { link = '@keyword' },
        ['@keyword.debug'] = { link = 'Debug' },
        ['@keyword.exception'] = { link = '@keyword' },
        ['@keyword.conditional'] = { link = 'Conditional' },
        ['@keyword.directive'] = { link = 'PreProc' },
        ['@punctuation.delimiter'] = { link = 'Delimiter' },
        ['@punctuation.bracket'] = { link = 'Delimiter' },
        ['@punctuation.special'] = { link = 'Special' },
        ['@comment'] = { link = 'Comment' },
        ['@comment.documentation'] = { link = '@comment' },
        ['@comment.error'] = { link = 'DiagnosticError' },
        ['@comment.warning'] = { link = 'DiagnosticWarn' },
        ['@comment.todo'] = { link = 'Todo' },
        ['@comment.note'] = { link = 'DiagnosticInfo' },
        ['@markup.strong'] = { bold = true },
        ['@markup.italic'] = { italic = true },
        ['@markup.strikethrough'] = { strikethrough = true },
        ['@markup.underline'] = { underline = true },
        ['@markup.heading'] = { link = 'Title' },
        ['@markup.heading.1'] = { fg = c.clay, bold = true },
        ['@markup.heading.2'] = { fg = c.sand, bold = true },
        ['@markup.heading.3'] = { fg = c.grass, bold = true },
        ['@markup.heading.4'] = { fg = c.tree, bold = true },
        ['@markup.heading.5'] = { fg = c.rock, bold = true },
        ['@markup.heading.6'] = { fg = c.fg, bold = true },
        ['@markup.quote'] = { link = 'Comment' },
        ['@markup.math'] = { link = 'Special' },
        ['@markup.link'] = { link = 'Underlined' },
        ['@markup.raw'] = { link = 'Special' },
        ['@markup.list'] = { link = 'Special' },
        ['@diff.plus'] = { link = 'Added' },
        ['@diff.minus'] = { link = 'Removed' },
        ['@diff.delta'] = { link = 'Changed' },
        ['@tag'] = { link = 'Special' },
        ['@tag.builtin'] = { link = '@tag' },
        ['@tag.attribute'] = { link = '@tag' },
        ['@tag.delimiter'] = { link = 'Delimiter' },

        -- LSP
        ['@lsp.type.function'] = {},

        -- Specifics
        netrwSymlink = { fg = c.moss },
        netrwExe = { fg = c.grass },
        ['@constructor.lua'] = { link = 'Delimiter' },
    }
end

return M
